@startuml

title Диаграмма Контекста - Приложение Управления Отоплением

!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

Person(client, "Клиент", "Пользователь управляет системой отопления через приложение")
Person(technician, "Специалист по подключению", "Подключает систему отопления к приложению на месте установки")

System(monoApp, "Система управления отоплением")

System_Ext(sensor, "Датчик температуры", "Собирает данные о температуре. Управляется и мониторится сервером")
System_Ext(heaterDevice, "Устройство отопления", "Контролируется приложением. Управляет температурой дома")

Rel(client, monoApp, "Управление отоплением и проверка температуры")
Rel(technician, monoApp, "Подключение устройства к системе")
Rel(monoApp, heaterDevice, "Контроль и управление")
Rel(monoApp, sensor, "Получение данных о температуре")

@enduml
